export const yearPicker = [
  { label: '--Select Year --', value: null },
  { label: 'FE', value: 'FE' },
  { label: 'SE', value: 'SE' },
  { label: 'TE', value: 'TE' },
  { label: 'BE', value: 'BE' },
];

export const branchPicker = [
  { label: '--Select Branch --', value: null },
  { label: 'Comp', value: 'C' },
  { label: 'IT', value: 'I' },
  { label: 'ENTC', value: 'E' },
];

export const batchPicker = {
  FE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: 'A', value: 'A' },
      { label: 'B', value: 'B' },
      { label: 'C', value: 'C' },
      { label: 'D', value: 'D' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: 'A', value: 'A' },
      { label: 'B', value: 'B' },
      { label: 'C', value: 'C' },
      { label: 'D', value: 'D' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: 'A', value: 'A' },
      { label: 'B', value: 'B' },
      { label: 'C', value: 'C' },
      { label: 'D', value: 'D' },
    ],
  },
  SE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: 'D', value: 'D' },
      { label: 'E', value: 'E' },
      { label: 'F', value: 'F' },
      { label: 'G', value: 'G' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
  },
  TE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
  },
  BE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: 'K', value: 'K' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'N', value: 'N' },
    ],
  },
};

export const divPicker = {
  FE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
  },
  SE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
  },
  TE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
    ],
    ENTC: [
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
  },
  BE: {
    Comp: [
      { label: '--Select Batch --', value: null },
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
    ],
    ENTC: [
      { label: '--Select Batch --', value: null },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
      { label: '7', value: '7' },
      { label: '8', value: '8' },
    ],
    IT: [
      { label: '--Select Batch --', value: null },
      { label: '9', value: '9' },
      { label: '10', value: '10' },
      { label: '11', value: '11' },
      { label: '12', value: '12' },
    ],
  },
};
